sonar.projectKey=bhbarquero-dev_uriyya-music-player
sonar.organization=bhbarquero-dev

sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.sources=src, tests

sonar.test.inclusions=**/*.test.ts,**/*.spec.ts,**/*.test.tsx,**/*.spec.tsx
sonar.coverage.exclusions=**/*.test.ts,**/test/**,**/__tests__/**

# This is the name and version displayed in the SonarCloud UI.
#sonar.projectName=uriyya-music-player
#sonar.projectVersion=1.0


# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8